### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by smiile8888** [smiile8888/blog#1]
- [x] posts don't load on production
- [ ] `nav` bar syncs with the main website
- [ ] fonts
- [x] touch-up on color palette
- [ ] `pre` and `code` block color touch-up
